// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBgvywZtQxcHxqSy0ZCBOE6flBg-TeV8A',
    appId: '1:530949737565:web:1badc268b0f7be3c0751b4',
    messagingSenderId: '530949737565',
    projectId: 'bus-booking-ticket',
    authDomain: 'bus-booking-ticket.firebaseapp.com',
    storageBucket: 'bus-booking-ticket.firebasestorage.app',
    measurementId: 'G-LK4W8RCYFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzW0qZLtEnOtPRg_4rZob0MHuTI3AdPD8',
    appId: '1:530949737565:android:ab4dadb168c3f7ec0751b4',
    messagingSenderId: '530949737565',
    projectId: 'bus-booking-ticket',
    storageBucket: 'bus-booking-ticket.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE_IZyofnxbxJNxojYm6G_CgLMI2EQjek',
    appId: '1:530949737565:ios:843d34c4a8182aec0751b4',
    messagingSenderId: '530949737565',
    projectId: 'bus-booking-ticket',
    storageBucket: 'bus-booking-ticket.firebasestorage.app',
    iosBundleId: 'com.example.busTicketApp',
  );
}
