// Mocks generated by Mockito 5.4.6 from annotations
// in bus_ticket_app/test/core/user/cubit/user_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i5;

import 'package:bus_ticket_app/core/user/user_service.dart' as _i2;
import 'package:bus_ticket_app/models/user_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i2.UserService {
  @override
  _i3.Future<_i4.MUser?> getUserInfo(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getUserInfo, [email]),
            returnValue: _i3.Future<_i4.MUser?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.MUser?>.value(),
          )
          as _i3.Future<_i4.MUser?>);

  @override
  _i3.Future<_i4.MUser?> getUserbyId(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserbyId, [id]),
            returnValue: _i3.Future<_i4.MUser?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.MUser?>.value(),
          )
          as _i3.Future<_i4.MUser?>);

  @override
  _i3.Future<List<_i4.MUser>> getAllUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUsers, []),
            returnValue: _i3.Future<List<_i4.MUser>>.value(<_i4.MUser>[]),
            returnValueForMissingStub: _i3.Future<List<_i4.MUser>>.value(
              <_i4.MUser>[],
            ),
          )
          as _i3.Future<List<_i4.MUser>>);

  @override
  _i3.Future<void> updateUserProfile(
    String? email,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [email, data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> uploadAvatar(String? email, _i5.Uint8List? imageBytes) =>
      (super.noSuchMethod(
            Invocation.method(#uploadAvatar, [email, imageBytes]),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<int?> getUserIdFromLocal() =>
      (super.noSuchMethod(
            Invocation.method(#getUserIdFromLocal, []),
            returnValue: _i3.Future<int?>.value(),
            returnValueForMissingStub: _i3.Future<int?>.value(),
          )
          as _i3.Future<int?>);
}
